name: uikit
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # uikit:
  im_uikit:
    path: packages/uikit

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0

  flutter_launcher_icons: ^0.14.3

  # Code generation
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0

flutter_gen:
  output: lib/gen
  integrations:
    flutter_svg: true
    lottie: true
  assets:
    enabled: true
    outputs:
      class_name: Assets
  fonts:
    enabled: true
    outputs:
      class_name: FontFamily

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: SuisseIntl
      fonts:
        - asset: assets/fonts/SuisseIntl-Regular.otf
          weight: 400
        - asset: assets/fonts/SuisseIntl-Medium.otf
          weight: 500
        - asset: assets/fonts/SuisseIntl-Semibold.otf
          weight: 600
        - asset: assets/fonts/SuisseIntl-Bold.otf
          weight: 700
  
